//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElempleoApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public decimal numero_identificacion { get; set; }
        public int codigo_ciudad { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
